root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/{{name}}"
  delay = 500
  exclude_dir = ["dist", "release", "tmp", "vendor"]
  include_ext = ["go"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[log]
  time = false

[misc]
  clean_on_exit = true
